Add manipulation environments
MichalBortkiewicz/JaxGCRL pull request #2
Opened 2024-10-02 23:46 UTC by SimpleGeometry

This PR adds 4-5 manipulation environments of varying difficulties, many are similar in flavor. In particular, it adds a reach and grasp task, and then three pick and place tasks: two without bins ("pickplace_easy" and "pickplace_hard") and one with bins ("binpick").

Environments work for MJX (positional is not advised/somewhat unstable still, and the other backends are much worse). Environments have been tested for collision/friction, stability, and speed, yielding around ~20k SPS on an A100 last checked (need to re-benchmark before merging though). If helpful, I can provide htmls for visualizations.

Also, refactors utils.py slightly.

2024-10-03 10:00 UTC, MichalBortkiewicz requested changes
Minor problem with `update_goal` and perhaps we might abstract some part that is the same for all the tasks in a single file?

2024-10-03 12:30 UTC, SimpleGeometry commented on envs/arm_binpick.py
> +        if backend == "mjx":
Perhaps I should disable positional for now -- I'd say positional is half-working. I made a lot of changes to try stabilizing it with mixed success, so I'd like to hold on to the positional XMLs, but at the moment MJX is probably the only one that makes sense to use. Will edit.

2024-10-03 12:31 UTC, SimpleGeometry commented on envs/arm_binpick.py
> +        return state.replace(info=updated_info)
Oops, yeah, this function I hadn't tested, I was planning on using it sometime before myself but currently am not.

2024-10-03 12:32 UTC, SimpleGeometry commented on envs/arm_binpick.py
> +class ArmBinpick(PipelineEnv):
Noted, will try to think about how to refactor this. Possible they can all go into one file even, or if not let me see what I can refactor into a separate file.

2024-10-03 16:37 UTC, SimpleGeometry commented on envs/arm_binpick.py
> +class ArmBinpick(PipelineEnv):
I know your initial suggestion might have been to refactor shared components into a single file, but it looked reasonable to refactor the entire files together into one file. Could you let me know if you think it's better this way or if I should still refactor it?

2024-10-05 08:08 UTC, MichalBortkiewicz approved these changes
Looks

2024-10-05 13:50 UTC, merged